import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.bg}>
        <div className={styles.header}>
          <h1>Folders</h1>
          <div className={styles.addNew}>
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M12 4V20M4 12H20"
                stroke="#4AA2F7"
                stroke-width="3"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </div>
        </div>

        <main className={`${styles.main}`}>
          <div className={styles.conatiner}>
            <div className={styles.mainFolder}>
              <div className={styles.folderRear}></div>
              <div className={styles.files}>
                <div className={styles.file}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>All Recipes</h2>
                <p>21 recipes</p>
              </div>
            </div>
          </div>
          <div className={styles.conatiner}>
            <div className={styles.mainFolder}>
              <div className={styles.folderRear}></div>
              <div className={styles.files}>
                <div className={styles.file}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>Dinner</h2>
                <p>14 recipes</p>
              </div>
            </div>
          </div>
          <div className={styles.conatiner}>
            <div className={styles.mainFolder}>
              <div className={styles.folderRear}></div>
              <div className={styles.files}>
                <div className={styles.file}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>Breakfast</h2>
                <p>7 recipes</p>
              </div>
            </div>
          </div>
          <div className={styles.conatiner}>
            <div className={styles.mainFolder}>
              <div className={styles.folderRear}></div>
              <div className={styles.files}>
                <div className={styles.file}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>Lunch</h2>
                <p>4 recipes</p>
              </div>
            </div>
          </div>
          <div className={styles.conatiner}>
            <div className={styles.mainFolder}>
              <div className={styles.folderRear}></div>
              <div className={styles.files}>
                <div className={styles.file}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>Brunch</h2>
                <p>12 recipes</p>
              </div>
            </div>
          </div>
          <div className={styles.conatiner}>
            <div className={`${styles.mainFolder} ${styles.unsorted}`}>
              <div
                className={`${styles.folderRear} ${styles.unsortedRear}`}
              ></div>
              <div className={styles.files}>
                <div className={`${styles.file}`}>
                  <Image
                    src="/Img.png"
                    className={styles.Img}
                    alt=""
                    // fill
                    height={32}
                    width={32}
                  />
                  <h3>Sweet Pastries</h3>
                </div>
                <div className={styles.file}></div>
                <div className={styles.file}></div>
              </div>
              <div className={styles.folderTitle}>
                <h2>Unsorted</h2>
                <p>2 recipes</p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
